version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "exodus-fork-12"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    target-branch: "exodus-fork-12"
    directory: "/"
    schedule:
      interval: "weekly"
